### ISSUE TITLE
Retries

### ISSUE THREAD

**Issue by dfarr** [resonatehq/roadmap#2]
User provided functions can be retried according to a user provided retry policy. If no retry policy is specified we must fallback to a sensible default. At minimum we should provide:
- linear retry
- exponential retry
- never

The retry should be timeout aware and never do an attempt once the durable promise timeout time has elapsed.

**Comment by flossypurse** [comment]
**status update**

This feature / functionality is implemented and supported in the Python SDK and TypeScript SDK.
